### ISSUE TITLE
jumping css while rendering the page in production

### ISSUE THREAD

**Issue by rolele** [strues/react-universal-boiler#16]
`yarn start`
It start like this:

![image](https://user-images.githubusercontent.com/22406571/27420830-03ab1090-576b-11e7-806a-1aff73b0fe6e.png)

and it render like this:
![image](https://user-images.githubusercontent.com/22406571/27420850-1ce1dada-576b-11e7-9479-c0d7cc16e21b.png)

This is a big issue I think. Do you have any idea what is the problem here?

**Comment by rolele** [comment]
It seems that the SSR is not doing all the work on the server-side.
Usually I can disable js on the client with SSR app and the app should render perfectly.
Here this is the result of disabling js:
<img width="964" alt="screen shot 2017-06-22 at 10 20 05 pm" src="https://user-images.githubusercontent.com/22406571/27433705-25998f32-5799-11e7-92e0-7408493b13e3.png">

The head tag is kind of empty.
If I re-enable js:
<img width="971" alt="screen shot 2017-06-22 at 10 22 16 pm" src="https://user-images.githubusercontent.com/22406571/27433739-49282670-5799-11e7-8bb0-0444884e436d.png">
Now head include the inline style and the meta.

Do you know how to get the full SSR behavior with with boilerplate

**Comment by strues** [comment]
I see what you're saying. I'll need to play around with styled-components some more. What's going on is the stylesheet generated by styled-components isn't populating in the head with JS disabled.

**Comment by rolele** [comment]
but this work should be done on the ssr side right? yeah ssr make it a little more complicated.
I found this boilerplate that does exactly that on the redux-ssr branch:
https://github.com/diegohaz/arc
It looks very nice.

**Comment by strues** [comment]
@rolele Nearly have a perfect implementation in place. Should be finished later this afternoon.

**Comment by rolele** [comment]
that is a great news. I like this starter very much. and I like to know that it is the basis of your boldr repo ( so it is a proof that it scales) thanks for the good work. I will test that and study your commit as soon as it is done.

**Comment by rolele** [comment]
Any news on this one?

**Comment by strues** [comment]
@rolele You should not have any more issues with css not loading properly when JS is disabled.

**Comment by otmjka** [comment]
There is PR [https://github.com/strues/react-universal-boiler/pull/18](url) where I've shown how to fix css jumping issue.

**Comment by otmjka** [comment]
@strues thanks for awesome boilerplate!
