### ISSUE TITLE
Styled components css Is not generated on the server

### ISSUE THREAD

**Issue by ilanus** [strues/react-universal-boiler#28]
It seems that after recent changes, the server does not compile styled-components chunks the className is there but css is empty. and there's an error from the console `Warning: Failed context type: Invalid context `__styled-components-stylesheet__` of type `StyleSheet` supplied to `Component`, expected instance of `StyleSheet`.` If Javascript is turned on everything is works fine, any idea what's missing?

**Comment by ilanus** [comment]
@strues It appears that `renderToNodeStream` returns the initial SSR render before all stylesheets were collected. I'm not sure what is a good solution around it?

**Comment by strues** [comment]
Fixing this right now.

**Comment by strues** [comment]
Fixed e0bd16720e128b41fb349e0b3046ee2f01abc90d

**Comment by ilanus** [comment]
Looks great! that's what I had in mind, do you think that using both `renderToString`, `renderToNodeStream` is fine in terms of performance?
